name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libusb-1.0-0-dev \
            libudev-dev

      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Build
        run: |
          source venv/bin/activate
          fbs freeze
          cd target
          tar cfJ flasher-linux.tar.xz "Sonix Keyboard Flasher"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flasher-linux
          path: target/flasher-linux.tar.xz
