name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install libusb-1.0-0-dev libudev-dev

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        source venv/bin/activate
        fbs freeze
        cd target
        tar cfJ flasher-linux.tar.xz "Sonix Keyboard Flasher"

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-linux
        path: target/flasher-linux.tar.xz
